### PR TITLE
Add Coding Mystery

### PR DESCRIPTION
**Pull request by Tulstrup**

### CODE REVIEW

**Comment by aloisdg** [comment]
You should disclose that this is your project. Is it FOSS?

**Comment by Tulstrup** [comment]
> You should disclose that this is your project. Is it FOSS?

There is a free mystery on the site that will give at least a couple of hours of free entertainment/learning.
There is also additional paid content on the site. Very similar to most of the other sites on the list.

Sorry for not disclosing that this is my own project, I was not aware of this requirement.

**Comment by aloisdg** [comment]
AFAIK this is is not a requirement, but more a convention. Self promotion is different than recommendation.

**Comment by Tulstrup** [comment]
> AFAIK this is is not a requirement, but more a convention. Self promotion is different than recommendation.

True. 

I hope this can get merged anyway, as I believe the site offers something valuable to those reading this list, while also being quite different than the resources that are already listed here.

**Pull request closed without merging**
