### PR TITLE
Add vAPI

### PR DESCRIPTION
**Pull request by aloisdg**
source: https://portswigger.net/daily-swig/introducing-vapi-an-open-source-lab-environment-to-learn-about-api-security

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the suggestion. We only want to list more accessable games.

**Comment by aloisdg** [comment]
What do you mean by that?

**Comment by vinkla** [comment]
The possibility to start the game without setup.

**Comment by aloisdg** [comment]
You can run it with docker without any specific configuration. This is not as vanilla as a webapp but it is easier than clicking a cookie popup.

**Pull request closed without merging**
